export const sliderItems = [
  {
    id: 1,
    img: "https://i.ibb.co/DG69bQ4/2.png",
    title: "SUMMER SALE",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
    bg: "f5fafd",
  },
  {
    id: 2,
    img: "https://i.ibb.co/DG69bQ4/2.png",
    title: "AUTUMN COLLECTION",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
    bg: "fcf1ed",
  },
  {
    id: 3,
    img: "https://i.ibb.co/cXFnLLV/3.png",
    title: "LOUNGEWEAR LOVE",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
    bg: "fbf0f4",
  },
];

export const categories = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/5886041/pexels-photo-5886041.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    title: "SHIRT STYLE!",
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/2983464/pexels-photo-2983464.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    title: "LOUNGEWEAR LOVE",
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/5480696/pexels-photo-5480696.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    title: "LIGHT JACKETS",
  },
];

export const popularProducts = [
  {
    id: 0,
    name: "Denim T-Shirt",
    img: "products/tshirt_01.webp",
    //img: "http://cdn.shopify.com/s/files/1/0635/7395/0708/products/404-page-not-found-t-shirt-polycoton-unisexe-291621.png?v=1654770601",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur, porro? Animi, nobis harum dolor architecto tempore in dicta et repudiandae? Sit consequuntur in magni suscipit eveniet quam voluptatem repudiandae velit?",
    price: 20,
    type: "t-shirt",
  },
  {
    id: 1,
    name: "Denim Shirt",
    img: "products/shirt_01.jpeg",
    //img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5mtR_28A1uTccBViflpf-3LcxUE0zTYfDqQ&usqp=CAU",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur, porro? Animi, nobis harum dolor architecto tempore in dicta et repudiandae? Sit consequuntur in magni suscipit eveniet quam voluptatem repudiandae velit?",
    price: 30,
    type: "shirt",
  },
  {
    id: 2,
    name: "Denim Shirt",
    img: "products/shirt_02.png",
    //img: "https://www.prada.com/content/dam/pradanux_products/U/UCS/UCS319/1YOTF010O/UCS319_1YOT_F010O_S_182_SLF.png",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur, porro? Animi, nobis harum dolor architecto tempore in dicta et repudiandae? Sit consequuntur in magni suscipit eveniet quam voluptatem repudiandae velit?",
    price: 25,
    type: "shirt",
  },
  {
    id: 3,
    name: "Denim Dress",
    img: "products/dress_01.png",
    //img: "https://www.burdastyle.com/pub/media/catalog/product/cache/7bd3727382ce0a860b68816435d76e26/107/BUS-PAT-BURTE-1320516/1170x1470_BS_2016_05_132_front.png",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur, porro? Animi, nobis harum dolor architecto tempore in dicta et repudiandae? Sit consequuntur in magni suscipit eveniet quam voluptatem repudiandae velit?",
    price: 35,
    type: "dress",
  },
  {
    id: 4,
    name: "Denim Bag",
    img: "products/bag_01.png",
    //img: "https://images.ctfassets.net/5gvckmvm9289/3BlDoZxSSjqAvv1jBJP7TH/65f9a95484117730ace42abf64e89572/Noissue-x-Creatsy-Tote-Bag-Mockup-Bundle-_4_-2.png",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur, porro? Animi, nobis harum dolor architecto tempore in dicta et repudiandae? Sit consequuntur in magni suscipit eveniet quam voluptatem repudiandae velit?",
    price: 10,
    type: "bag",
  },
  {
    id: 5,
    name: "Denim Hat",
    img: "products/hat_01.png",
    //img: "https://d3o2e4jr3mxnm3.cloudfront.net/Rocket-Vintage-Chill-Cap_66374_1_lg.png",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur, porro? Animi, nobis harum dolor architecto tempore in dicta et repudiandae? Sit consequuntur in magni suscipit eveniet quam voluptatem repudiandae velit?",
    price: 55,
    type: "hat",
  },
  {
    id: 6,
    name: "Denim T-Shirt",
    img: "products/tshirt_02.png",
    //img: "https://d3o2e4jr3mxnm3.cloudfront.net/Mens-Jake-Guitar-Vintage-Crusher-Tee_68382_1_lg.png",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur, porro? Animi, nobis harum dolor architecto tempore in dicta et repudiandae? Sit consequuntur in magni suscipit eveniet quam voluptatem repudiandae velit?",
    price: 65,
    type: "t-shirt",
  },
  {
    id: 7,
    name: "Denim Coat",
    img: "products/coat_01.png",
    //img: "https://www.pngarts.com/files/3/Women-Jacket-PNG-High-Quality-Image.png",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur, porro? Animi, nobis harum dolor architecto tempore in dicta et repudiandae? Sit consequuntur in magni suscipit eveniet quam voluptatem repudiandae velit?",
    price: 33,
    type: "coat",
  },
];
